version: '3' 
services: 
  ftp-server: 
    image: fauria/vsftpd 
    container_name: ftp-server 
    ports: 
      - "20:20" 
      - "21:21" 
      - "21100-21110:21100-21110" 
    environment: 
      - FTP_USER=admin 
      - FTP_PASS=passadmin
      - PASV_ADDRESS=172.21.0.2
      - PASV_MIN_PORT=21100 
      - PASV_MAX_PORT=21110 
    volumes: 
      - ./ftp-data:/home/vsftpd 
    restart: always 
